import { TRPCError } from "@trpc/server";

import { ssoService } from "@/services/auth/sso.service";

import { SSOExchangeCodeSchema } from "@/schemas/auth";

import { ssoConfig } from "@/config";

import { rateLimitedPublicProcedure, router } from "@/trpc/trpc";

import { te } from "@/i18n";

/**
 * SSO router
 * Handles SSO configuration queries and auth code exchange
 */
export const ssoRouter = router({
  /**
   * Get SSO configuration for the frontend
   * Returns whether SSO is enabled and the button label
   */
  getConfig: rateLimitedPublicProcedure.query(async () => {
    return {
      enabled: ssoConfig.enabled,
      buttonLabel: ssoConfig.buttonLabel,
      type: ssoConfig.type,
    };
  }),

  /**
   * Exchange a temporary SSO auth code for a JWT token
   * The auth code is generated by the SSO callback controller after successful IdP authentication
   */
  exchangeCode: rateLimitedPublicProcedure
    .input(SSOExchangeCodeSchema)
    .mutation(async ({ input, ctx }) => {
      if (!ssoConfig.enabled) {
        throw new TRPCError({
          code: "SERVICE_UNAVAILABLE",
          message: te(ctx.locale, "auth.ssoNotEnabled"),
        });
      }

      const result = await ssoService.exchangeAuthCode(input.code);

      if (!result) {
        throw new TRPCError({
          code: "BAD_REQUEST",
          message: te(ctx.locale, "auth.invalidOrExpiredSSOCode"),
        });
      }

      return {
        token: result.jwt,
        user: result.user,
        isNewUser: result.isNewUser,
      };
    }),
});
