-- AlterTable
ALTER TABLE "Company" ADD COLUMN "storageMode" TEXT NOT NULL DEFAULT 'MEMORY_ONLY';
ALTER TABLE "Company" ADD COLUMN "retentionDays" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Company" ADD COLUMN "encryptData" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Company" ADD COLUMN "autoDelete" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Company" ADD COLUMN "consentGiven" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Company" ADD COLUMN "consentDate" TIMESTAMP(3);
