name: ✨ Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please fill out the form below.

  - type: dropdown
    id: edition
    attributes:
      label: Edition
      description: Which edition are you using?
      options:
        - Community Edition (Open Source)
        - Enterprise Edition (Licensed)
        - Cloud/SaaS
        - Not applicable
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe
      placeholder: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: A clear and concise description of what you want to happen
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered
      placeholder: A clear description of any alternative solutions or features you've considered

  - type: dropdown
    id: category
    attributes:
      label: Category
      description: What category does this feature fall under?
      options:
        - UI/UX
        - Performance
        - Security
        - Core Functionality
        - Documentation
        - Integration (Slack, Webhooks, etc.)
        - Alerting
        - Workspace Management
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would be helpful
        - High - Important for my use case
        - Critical - Blocking my workflow
    validations:
      required: true

  - type: textarea
    id: usecase
    attributes:
      label: Use Case
      description: Describe a specific use case for this feature
      placeholder: How would you use this feature? What problem would it solve for you?
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or examples about the feature request
      placeholder: Any additional information, screenshots, or examples

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues to ensure this feature has not already been requested
          required: true
        - label: I have provided all the information requested above
          required: true

