#!/usr/bin/env node

/**
 * Self-Hosted Setup Script
 * Generates secure secrets for JWT_SECRET, ENCRYPTION_KEY, and POSTGRES_PASSWORD
 *
 * Usage (from project root):
 *   pnpm setup:selfhosted              - Display generated secrets
 *   pnpm setup:selfhosted --write      - Write secrets to .env file at project root
 *   pnpm setup:selfhosted --append     - Append secrets to existing .env file at root
 */

import { randomBytes } from "node:crypto";
import { dirname, join } from "node:path";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

// Get project root (2 levels up from this script)
const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const PROJECT_ROOT = join(__dirname, "..", "..", "..");

function generateSecret(length: number = 64): string {
  return randomBytes(length).toString("base64");
}

function main() {
  const args = process.argv.slice(2);
  const shouldWrite = args.includes("--write");
  const shouldAppend = args.includes("--append");

  console.log("\n🚀 Qarote Self-Hosted Setup");
  console.log("=".repeat(80));
  console.log("Generating secure secrets for your installation...\n");

  // Generate secrets
  const jwtSecret = generateSecret(64);
  const encryptionKey = generateSecret(64);
  const postgresPassword = generateSecret(32);

  console.log("✅ Generated secrets:\n");
  console.log(`JWT_SECRET="${jwtSecret}"`);
  console.log(`ENCRYPTION_KEY="${encryptionKey}"`);
  console.log(`POSTGRES_PASSWORD="${postgresPassword}"`);

  // Handle writing to file
  if (shouldWrite || shouldAppend) {
    const envPath = join(PROJECT_ROOT, ".env");
    let envContent = "";

    if (shouldAppend && existsSync(envPath)) {
      envContent = readFileSync(envPath, "utf-8");
      if (!envContent.endsWith("\n")) {
        envContent += "\n";
      }
      envContent += "\n# Security Secrets (Generated by setup-selfhosted.ts)\n";
    } else {
      envContent = "# Security Secrets (Generated by setup-selfhosted.ts)\n";
    }

    envContent += `JWT_SECRET="${jwtSecret}"\n`;
    envContent += `ENCRYPTION_KEY="${encryptionKey}"\n`;
    envContent += `POSTGRES_PASSWORD="${postgresPassword}"\n`;

    writeFileSync(envPath, envContent, "utf-8");

    console.log("\n✅ Secrets written to:", envPath);
    console.log(
      shouldAppend ? "(appended to existing file)" : "(created new file)"
    );
  } else {
    console.log("\n📝 To save these secrets:");
    console.log("   1. Copy the secrets above");
    console.log("   2. Add them to your .env file at project root");
    console.log("   3. Or run: pnpm setup:selfhosted --write");
  }

  console.log("\n⚠️  IMPORTANT SECURITY NOTES:");
  console.log("• Keep these secrets secure and private");
  console.log("• Use different secrets for different environments");
  console.log("• Never commit .env file to version control");
  console.log("• Store production secrets in secure key management systems");
  console.log("• Backup these secrets - they cannot be recovered if lost");
  console.log("=".repeat(80) + "\n");
}

main();
